### ISSUE TITLE
IOSXR_CLI.YML output.stdout_lines issue

### ISSUE THREAD

**Issue by panky00** [ios-xr/iosxr-ansible#1]
Hello,
  While I am trying to run the playbook IOSXR_CLI.YML. It's giving the below error. 

ok: [192.168.56.107] => {
    "output.stdout_lines": [
        "/bin/sh: 1: source: not found", 
        "nsenter: failed to execute xr_cli: No such file or directory"

**Comment by aermongk** [comment]
Are you using 32- or 64-bit IOS-XR?  32-bit XR doesn't support "remote" mode.  Try using iosxr_cli.yml in "local" subdirectory.

**Comment by panky00** [comment]
Thank you for your reply. Yes you are right, I am using 32bit ios_xr. But the thing is, This is the ouput of local uosxr-cli.yml. There is other playbook in cli sub directory. I am able to run them succesfully. please find the output of one of them playbook.

cisco@osboxes:~/iosxr-ansible/iosxr-ansible/local/samples/cli$ ansible-playbook cli_get_config.yml 

PLAY [ss-xr] *******************************************************************

TASK [iosxr_command] ***********************************************************
ok: [192.168.56.107]

TASK [debug] *******************************************************************
ok: [192.168.56.107] => {
    "output.stdout_lines": [
        [
            "", 
            "Wed Jul  6 09:38:45.084 UTC", 
            "Building configuration...", 
            "!! IOS XR Configuration 5.3.0", 
            "!! Last configuration change at Mon Jul  4 13:42:27 2016 by cisco", 
            "!", 
            "hostname R3", 
            "interface MgmtEth0/0/CPU0/0", 
            " shutdown", 
            "!", 
            "interface GigabitEthernet0/0/0/0", 
            " ipv4 address 192.168.56.107 255.255.255.0", 
            "!", 
            "interface GigabitEthernet0/0/0/1", 
            " description config by Ansible", 
            " ipv4 address 10.0.0.25 255.255.255.0", 
            "!", 
            "interface preconfigure GigabitEthernet0/0/0/2", 
            "!", 
            "ssh server v2", 
            "ssh server netconf port 57722", 
            "ssh server logging", 
            "xml agent ssl", 
            "!", 
            "xml agent tty", 
            "!", 
            "netconf agent tty", 
            "!", 
            "netconf-yang agent ssh", 
            "end", 
            ""
        ]
    ]
}

PLAY RECAP *********************************************************************
192.168.56.107             : ok=2    changed=0    unreachable=0    failed=0

**Comment by aermongk** [comment]
Without knowing what does your playbook look liked, you had said that you were using iosxr_cli.yml and failed with the error message, I can only assume that you are trying to do "run" command on IOS-XR console to access the ksh shell and then attempted to use TPNNS.  TPNNS and xr_cli are not supported on 32-bit QNX IOS-XR.
