### ISSUE TITLE
Difference between this repository and Ansible XR core module?

### ISSUE THREAD

**Issue by remingtonc** [ios-xr/iosxr-ansible#3]
Could anyone provide a quick explanation on the differences between this and the XR core module?
https://github.com/ansible/ansible-modules-core/tree/devel/network/iosxr

Is this a collection of playbooks/utilities/scripts/examples using the XR core module?

**Comment by aermongk** [comment]
These ios-xr/iosxr-ansible playbooks/modules are collection of examples that you could do to communicate with IOS-XR.  As mentioned in the README, there are 7 different ways to configure IOS-XR and these playbooks and modules show how to use it.

You can also use the ones in ansible core module if you so desire.
