### ISSUE TITLE
Empty returns on get_facts?

### ISSUE THREAD

**Issue by remingtonc** [ios-xr/iosxr-ansible#4]
Using last release and master branch both result in nothing being returned from the remote host despite being marked as "ok". This is an issue with both local and remote mode. Last release mentions breaking changes, is this repo still functional?

If not, are there pointers to accomplishing the same things?

```
vagrant@vagrant:~/iosxr-ansible-0.1.6/remote$ ansible-playbook samples/iosxr_get_facts.yml

PLAY [ss-xr] ******************************************************************************************************************************************************************************************

TASK [get system facts] *******************************************************************************************************************************************************************************
 [WARNING]: Module did not set no_log for password

ok: [11.1.1.10]

TASK [debug] ******************************************************************************************************************************************************************************************
ok: [11.1.1.10] => {
    "changed": false,
    "facts": {
        "changed": false,
        "show arp": [],
        "show filesystem": [],
        "show install active": [],
        "show inventory all": [],
        "show ipv4 int brief": [],
        "show ipv6 int brief": [],
        "show license all": [],
        "show media": [],
        "show memory summary": [],
        "show platform": [],
        "show route": [],
        "show running-config": [],
        "show version": [],
        "warnings": [
            "Module did not set no_log for password"
        ]
    }
}

PLAY RECAP ********************************************************************************************************************************************************************************************
11.1.1.10                  : ok=2    changed=0    unreachable=0    failed=0
```
@skkumaravel

**Comment by aermongk** [comment]
I just ran the same "iosxr_get_facts.yml" playbook and it had no problem, although I didn't use vagrant.  Please verify that you can manually "ssh" to the XR without password and be able to run XR command through that ssh session, basically Ansible just automated those sequence.

Interestingly, I have never seen this "warnings: Module did not set no_log for password" before.  That may be your clue.  Have you tried other playbooks, e.g. iosxr_cli.xml or run script "show_users".

FYI, Ansible core network module has provided another get_facts with formatted output if that is what you are trying to do.

**Comment by aermongk** [comment]
The current iosxr-ansible can only support up to Ansible 2.3 Core/Network.
