### ISSUE TITLE
How to convert the device public RSA key in hexadecimal format to a .pub SSH key?

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ios-xr/iosxr-ansible#5]
@aermongk 
This hexadecimal format is a nightmare to convert to a pub SSH format.
```
RP/0/0/CPU0:XRv_Spine_01#show crypto key mypubkey rsa
Wed May 17 15:15:58.245 UTC
Key label: the_default
Type     : RSA General purpose
Size     : 2048
Created  : 14:25:05 UTC Wed May 17 2017
Data     : 
 30820122 300D0609 2A864886 F70D0101 01050003 82010F00 3082010A 02820101 
 008CCD6E AFF55524 147A7C17 0EEE8B78 0CA63452 ED20E0E2 7CFAC946 ADE2047C 
 A130F1B7 6D433B00 E4C4E566 2DED8E72 CE945A97 E284CB52 17450ECC C1C34BC9 
 F55A7990 BE8D3334 9906D711 111C3EC5 C749CE8B E888F6C6 F8AC4E94 EF914967 
 CDEECDA4 3E4D2DE5 ECC53312 C67BAFEB 0CAFA85F 74ECC07C F47030CA 1AA3972B 
 965CC235 EDFCBE84 E825B640 F7ADC602 3E9C93DD 2C9B4E05 103FCE40 D6400EB8 
 4F15C473 B7CDCCED 701DDF87 859F090E 5ABD6C41 7F735F9C D7CDCE32 D56D6DEE 
 FC42EC9A 47CDB617 BF70FDA2 0FC78354 2613FFEE A2E5D9B1 095C48DB 6A8B562E 
 32C46C2A B58D8AAB B9C1C314 2F158E61 B948CA95 7A62CD1C 5AB33C45 A01CE8D9 
 23020301 0001
```
I know how to convert a base64 pem to a SSH .pub format (binary DER).
Do you know how to convert the hexadecimal format to a base64 pem or directly to a .pub standard format on Linux?

Wouldn't it be much simpler and easier for everyone to show the IOS-XR device public key in a .pub format as on NX-OS for instance?
```

**Comment by aermongk** [comment]
>>> Do you know how to convert the hexadecimal format to a base64 pem or directly to a .pub standard format on Linux?
- I have never looked into it.

>>> Wouldn't it be much simpler and easier for everyone to show the IOS-XR device public key in a .pub format as on NX-OS for instance?
- Can't say.
